name: CI

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build Openglobus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/main
      - run: npm run build

  test:
    name: Running tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/main
      - run: npm test

  docs:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/main
      - run: npm run docs
#        Temprorary deploy to check work
      - name: Deploy to openglobus.github.io
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY  }}
        with:
          source-directory: docs
          destination-github-username: openglobus
          destination-repository-name: openglobus.github.io
          user-name: Github Bot
          user-email: github-actions[bot]@users.noreply.github.com
          target-branch: master
          target-directory: docs

  generate_types:
    name: Generate types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/main
      - run: npm run generate_types